CREATE DATABASE asdexTechPage;

USE asdexTechPage;

CREATE TABLE admin(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    usuario VARCHAR(10) NOT NULL, 
    clave VARCHAR(10) NOT NULL
);

CREATE TABLE proyectos(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    detalle VARCHAR(50) NOT NULL
);

CREATE TABLE header(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    activo INT
);

CREATE TABLE apk(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    logo VARCHAR(50) NOT NULL,
    archivo VARCHAR(50) NOT NULL,
    descrip VARCHAR(50) NOT NULL,
    activo INT
);

CREATE TABLE blog(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    tittle VARCHAR(50) NOT NULL,
    img VARCHAR(50) NOT NULL,
    descrip VARCHAR(50) NOT NULL
);

CREATE TABLE teamMembers(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    img VARCHAR(50) NOT NULL
);

